name: 'weblocopener'
summary: WeblocOpener can open, edit, create .webloc files on Debian GNU/Linux.
description: |
  WeblocOpener is a simple way to open, edit, create MacOS Safari .webloc files on Windows and Debian GNU/Linux.
version: '2.0.0'
license: Apache-2.0

#todo add here parts, see: https://snapcraft.io/docs/java-applications

# snapcraft clean
# snapcraft snap --debug
# if error... file exists - rm file
# snap install weblocopener_2.0.0_amd64.snap --dangerous
# weblocopener
# snap remove weblocopener
adopt-info: weblocopener
base: core18
parts:
  weblocopener:
    # See 'snapcraft plugins'
    plugin: maven
    source: ./
    parse-info:
      - weblocopener.metainfo.xml

  libraries-weblocopener:
    source: ./target/lib/
    organize:
      '*.jar*': jar/lib/
    plugin: dump

#apps:
#  weblocopener:
#    environment:
#      JAVA_HOME: $SNAP/usr/lib/jvm/java-1.8.0-openjdk-amd64
#      PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
#    command: ls

apps:
  weblocopener:
    command: java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/WeblocOpenerCore.jar

#    desktop: build/WeblocOpener.desktop
#    common-id: com.github.benchdoos.weblocopener

#    command: desktop-launch \
#      $SNAP/freeplane-1.6.10/freeplane.sh